baseURL = ""
languageCode = "ru"
title = "Московский металлургический завод 'Серп и молот'. 130 лет истории - от пахотных земель до современного жилого квартала"
assetDir = "assets"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "sitemap", "RSS", "404", "robotsTXT", "section"]

