baseURL = ""
languageCode = "ru"
title = "«Лефортовский треугольник» — история московского завода «Серп и молот»"
assetDir = "assets"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "sitemap", "RSS", "404", "robotsTXT", "section"]

